---
name: busted
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install luajit
        run: |
          sudo apt-get -y update &&
          sudo apt-get -y upgrade &&            
          sudo apt-get -y install luajit luarocks

      - name: Install nlua using luarocks make
        run: luarocks make --local

      - name: Run tests
        run: |
          eval $(luarocks path --lua-version 5.1 --local) && luarocks test --local
